import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import Navbar from "@/app/components/Navbar";
import Buttombar from "./components/Buttombar";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gowilds - Tours and Travels",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
//    const heads = headers()

//  const pathname = heads.get('next-url')
// console.log(pathname)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Navbar />
        {props.children}
        <Footer />
        {/* {pathname==='/explore'?null:<Footer />} */}
        <Buttombar />

      </body>
    </html>
  );
}
